[build]
  publish = "dist"
  command = "npm install && npm run build"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/love"
  to = "https://jiangyingjuner.notion.site/8ada7240c1024d799309f3ca6ec863bf"
  force = true

[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

